# -*- coding: utf-8 -*-
"""DAE Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msiSzAQU_cJp0Y0NHkzRxG4sMrFXSq6y

#***DAE Group Project***
*A Statistical Approach with RCBD & Factorial Design*

##***Data Overview***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = "/content/big4_financial_risk_compliance.csv"
df = pd.read_csv(file_path)

# Dataset Overview
print("Dataset Overview:")
print(df.head())
print(df.info())
print(df.describe())

"""## ***Data Visualization***"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='AI_Used_for_Auditing', y='Audit_Effectiveness_Score', data=df)
plt.title('Audit Effectiveness Score by AI Usage')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Firm_Name', y='Audit_Effectiveness_Score', data=df)
plt.title('Audit Effectiveness Score by Firm Name')
plt.show()

"""## ***Randomized Complete Block Design (RCBD)***"""

# Factor: AI_Used_for_Auditing (Yes/No)
# Blocking Factor: Firm_Name (EY, PwC, Deloitte, KPMG)
# Response Variable: Audit_Effectiveness_Score

# Filtering necessary columns
df_rcbd = df[['Firm_Name', 'AI_Used_for_Auditing', 'Audit_Effectiveness_Score']]

# Convert categorical variables to numerical format
df_rcbd['AI_Used_for_Auditing'] = df_rcbd['AI_Used_for_Auditing'].map({'Yes': 1, 'No': 0})

# Heatmap of Audit Effectiveness Score by Firm & AI Usage
heatmap_data = df_rcbd.pivot_table(values="Audit_Effectiveness_Score", index="Firm_Name", columns="AI_Used_for_Auditing")
plt.figure(figsize=(6,5))
sns.heatmap(heatmap_data, annot=True, cmap="coolwarm")
plt.title("Audit Effectiveness Score Heatmap")
plt.show()

# Compute means
grand_mean = df_rcbd['Audit_Effectiveness_Score'].mean()
factor_means = df_rcbd.groupby('AI_Used_for_Auditing')['Audit_Effectiveness_Score'].mean()
block_means = df_rcbd.groupby('Firm_Name')['Audit_Effectiveness_Score'].mean()

# Compute Sum of Squares (SS)
SS_total = ((df_rcbd['Audit_Effectiveness_Score'] - grand_mean) ** 2).sum()
SS_factor = sum(df_rcbd.groupby('AI_Used_for_Auditing').size() * (factor_means - grand_mean) ** 2)
SS_block = sum(df_rcbd.groupby('Firm_Name').size() * (block_means - grand_mean) ** 2)
SS_error = SS_total - SS_factor - SS_block

# Compute Degrees of Freedom (DOF)
df_factor = len(factor_means) - 1
df_block = len(block_means) - 1
df_error = len(df_rcbd) - (df_factor + df_block + 1)

# Compute Mean Squares and F-statistics (MS)
MS_factor = SS_factor / df_factor
MS_block = SS_block / df_block
MS_error = SS_error / df_error
F_factor = MS_factor / MS_error

# Create RCBD ANOVA Table
df_anova_rcbd = pd.DataFrame({
    "Source": ["AI Used", "Firm Name", "Error"],
    "SS": [SS_factor, SS_block, SS_error],
    "DF": [df_factor, df_block, df_error],
    "MS": [MS_factor, MS_block, MS_error],
    "F": [F_factor, np.nan, np.nan]
})
print(df_anova_rcbd)

"""## ***Factorial Design***"""

# Factors: AI_Used_for_Auditing (Yes/No) and Employee_Workload (Low, Medium, High)
# Response Variable: Audit_Effectiveness_Score

# Filtering necessary columns
df_factorial = df[['AI_Used_for_Auditing', 'Employee_Workload', 'Audit_Effectiveness_Score']]

# Convert categorical variables to numerical format
df_factorial['AI_Used_for_Auditing'] = df_factorial['AI_Used_for_Auditing'].map({'Yes': 1, 'No': 0})
df_factorial['Employee_Workload'] = pd.cut(df_factorial['Employee_Workload'], bins=[0, 50, 70, 100], labels=['Low', 'Medium', 'High'])

# Interaction Plot (Factorial Design) - AI vs. Workload vs. Audit Score
plt.figure(figsize=(8,5))
sns.pointplot(data=df_factorial, x='Employee_Workload', y='Audit_Effectiveness_Score', hue='AI_Used_for_Auditing')
plt.xlabel("Workload Level")
plt.ylabel("Audit Effectiveness Score")
plt.title("Interaction Effect of AI Usage and Workload on Audit Effectiveness")
plt.show()

# Compute means
grand_mean = df_factorial['Audit_Effectiveness_Score'].mean()
factor_means = df_factorial.groupby(['AI_Used_for_Auditing', 'Employee_Workload'])['Audit_Effectiveness_Score'].mean()
main_effects = df_factorial.groupby('AI_Used_for_Auditing')['Audit_Effectiveness_Score'].mean()
interaction_means = df_factorial.groupby(['AI_Used_for_Auditing', 'Employee_Workload'])['Audit_Effectiveness_Score'].mean()

# Compute Sum of Squares (SS)
SS_total = ((df_factorial['Audit_Effectiveness_Score'] - grand_mean) ** 2).sum()
SS_factor1 = sum(df_factorial.groupby('AI_Used_for_Auditing').size() * (main_effects - grand_mean) ** 2)
SS_factor2 = sum(df_factorial.groupby('Employee_Workload').size() * (df_factorial.groupby('Employee_Workload')['Audit_Effectiveness_Score'].mean() - grand_mean) ** 2)
SS_interaction = sum(df_factorial.groupby(['AI_Used_for_Auditing', 'Employee_Workload']).size() * (interaction_means - grand_mean) ** 2)
SS_error = SS_total - SS_factor1 - SS_factor2 - SS_interaction

# Compute Degrees of Freedom (DOF)
df_factor1 = len(main_effects) - 1
df_factor2 = len(df_factorial['Employee_Workload'].unique()) - 1
df_interaction = df_factor1 * df_factor2
df_error = len(df_factorial) - (df_factor1 + df_factor2 + df_interaction + 1)

# Compute Mean Squares and F-statistics
MS_factor1 = SS_factor1 / df_factor1
MS_factor2 = SS_factor2 / df_factor2
MS_interaction = SS_interaction / df_interaction
MS_error = SS_error / df_error
F_factor1 = MS_factor1 / MS_error
F_factor2 = MS_factor2 / MS_error
F_interaction = MS_interaction / MS_error

# Create Factorial ANOVA Table
df_anova_factorial = pd.DataFrame({
    "Source": ["AI Used", "Workload", "Interaction", "Error"],
    "SS": [SS_factor1, SS_factor2, SS_interaction, SS_error],
    "DF": [df_factor1, df_factor2, df_interaction, df_error],
    "MS": [MS_factor1, MS_factor2, MS_interaction, MS_error],
    "F": [F_factor1, F_factor2, F_interaction, np.nan]
})
print(df_anova_factorial)